
<form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php $_order = $this->getInvoice()->getOrder() ?>
    <?php echo $this->getChildHtml('order_info') ?>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-left">
    <?php else: ?>
    <div class="box-right">
    <?php endif; ?>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <div><?php echo $this->getChildHtml('order_payment') ?></div>
                <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
            </div>
            <fieldset>
                <div>
                    <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>
                   

                    <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    
					<?php $_incl = $this->displayShippingPriceInclTax($_order); ?>
					<br />
                     <?php echo $this->helper('sales')->__('Total Shipping Charges'); ?>:
                    <?php echo $_excl; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>
                    
                    
                     <br />
                    <?php 
					 $szOrderId = $_order->getSwipezoomOrderNumberTemp();
					 if($szOrderId){
						 $counts = Mage::getModel('internationalshipping/shipmentdetail')->getCollection()->addFieldToFilter('swipezoomorderid',$szOrderId);
						 if(count($counts)){
							foreach($counts as $sh)	{
								echo "Pickup Due : ".$sh->getPickupdue();
							}
						}
					 }
					
					?>
                </div>
                
                
                <?php if($swipwzoomorder = $_order->getSwipezoomOrderNumberTemp()){ ?> 
				
				<style>
                .entry-edit-head .tools a{display:none;}
				.swipezoom-container .price-notice {    float: right;}
				.swipezoom-container {    width: 50%;}
                </style>
				<?php }else{ ?> 
                <?php if ($this->canCreateShipment() && $this->canShipPartiallyItem()): ?>
                <p class="nm">
                    <label for="invoice_do_shipment" class="normal"><?php echo Mage::helper('sales')->__('Create Shipment') ?></label>
                    <input type="checkbox" name="invoice[do_shipment]" id="invoice_do_shipment" value="1" <?php echo $this->hasInvoiceShipmentTypeMismatch()?' disabled="disabled"':'' ?> />
                </p>
                <?php if ($this->hasInvoiceShipmentTypeMismatch()): ?>
                    <small><?php echo $this->__('Some items in this order have different invoice and shipment types. You can create shipment only after the invoice is created.') ?></small>
                    <?php endif; ?>
                <?php endif; ?>
                <?php } ?>
                
                
                
                <div id="tracking" style="display:none;"><?php echo $this->getChildHtml('tracking',false) ?></div>
            </fieldset>
        </div>
    </div>
    <?php endif; ?>
    <div class="clear"></div>
  <?php 
	  $shippingMethod = $_order->getData("shipping_method") ;
              //  if(strpos($shippingMethod,"swipezoom") !== FALSE){ 
			  if($swipwzoomorder = $_order->getSwipezoomOrderNumberTemp()){?>
					<div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Swipezoom Order Information') ?></h4>
            </div><fieldset>

                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Swipezoom Order #') ?><span class="price-notice"><span class="price">
                            <?php echo $_order->getSwipezoomOrderNumberTemp();  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Shipping Charges : ') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderShippingCharges(),true,false);  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Prepaid duties &amp; taxes : ') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderDutiesTaxes(),true,false);  ?></span></span></label>
                </div>

                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Insurance :') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderInsuranceCharges(),true,false);  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Duties Taxes Prepaid :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderDutiesTaxPrepaid() == "Y")?"Yes":"No";  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Insurance Paid :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderInsurancePaid() == "Y")?"Yes":"No";  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Confirmation Call :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderConfirmed() == "1")?"Ok":"Error";  ?>
                            </span></span></label>
                </div>
                
                <?php if($_order->getSwipezoomOrderConfirmed() == 0): ?>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Error Message :') ?><span class="price-notice"><span class="price"><?php echo $_order->getSwipezoomOrderConfirmedErrormessage();; ?>
                            </span></span></label>
                </div>
                <?php endif; ?>
               </fieldset>
            </div>
					
				<?php } ?>
    <div class="clear"></div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <?php
                $_itemsGridLabel = $this->getForcedShipmentCreate()?'Items to Invoice and Ship':'Items to Invoice';
            ?>
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('%s', $_itemsGridLabel) ?></h4>
        </div>
    </div>

    <div id="invoice_item_container">
          <?php echo $this->getChildHtml('order_items') ?>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var createShipment = $('invoice_do_shipment');
    createShipment.observe('click', function(e){
        if (createShipment.checked) {
            document.getElementById('tracking').style.display = 'block';
        } else {
            document.getElementById('tracking').style.display = 'none'
        }
    })

    /*forced creating of shipment*/
    var forcedShipmentCreate = <?php echo $this->getForcedShipmentCreate() ?>;
    var shipmentElement = $('invoice_do_shipment');
    if (forcedShipmentCreate && shipmentElement) {
        shipmentElement.checked = true;
        shipmentElement.disabled = true;
        document.getElementById('tracking').style.display = 'block';
    }
//]]>
</script>
