
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th width="70"><?php echo Mage::helper('sales')->__('Item') ?></th>
                <th width="120"><?php echo Mage::helper('sales')->__('Box Code') ?></th>
                <th width="70"><?php echo Mage::helper('sales')->__('Box No.') ?></th>
                <th width="500"><?php echo Mage::helper('sales')->__('Product Description') ?></th>
                <th width="150"><?php echo Mage::helper('sales')->__('Product Code') ?></th>
                <th width="70"><?php echo Mage::helper('sales')->__('Quantity') ?></th>
            </tr>
        </thead>
        <?php 
		$orderid = Mage::app()->getRequest()->getParam('order_id');
		$order= Mage::getModel('sales/order')->load($orderid);
		$swipwzoomorder = $order->getSwipezoomOrderNumberTemp();
		
		$_items = Mage::getModel('internationalshipping/packingdetail')->getCollection()->addFieldToFilter('swipezoomorderid',$swipwzoomorder); ?>
        <tbody class="<?php echo $_i%2?'even':'odd' ?>">
		<?php $_i=0;foreach ($_items as $_item): ?>
         <?php if(!$_item->getProductcode()){break;}
		$products = Mage::getModel('catalog/product')->loadByAttribute('sku', $_item->getProductcode());
		if(!$products){ echo "<tr ><td colspan='6'>Somthing wrong Happen - Product not found.</td></tr>"; break;}
		?>
        <?php $_i++; ?>
        	<tr class="border">
            <td><?php echo $_i ?></td>
		    <td><?php echo $_item->getBoxcode() ?></td>
            <td><?php echo $_item->getBoxno() ?></td>
            <td><?php 	echo $products = Mage::getModel('catalog/product')->loadByAttribute('sku', $_item->getProductcode())->getName(); 											//$productname = $_Pdetails->getName();
//			 $_item->getProductname() ?></td>
            <td><?php echo $_item->getProductcode() ?></td>
            <td><?php echo $_item->getProductqty() ?></td>
			</tr>
       <?php endforeach; ?>
        </tbody>
    </table>
  </div>
</div>