
<?php $_order = $this->getOrder() ?>
<?php
    $orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
    $orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
                $_email = Mage::helper('sales')->__('the order confirmation email was sent');
                else:
                $_email = Mage::helper('sales')->__('the order confirmation email is not sent');
                endif; ?>
        <div class="entry-edit-head">
          <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?><?php if($swipwzoomorder = $_order->getSwipezoomOrderNumberTemp()){ }else{ ?>  (<?php echo $_email ?>) <?php } ?></h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
           <?php if($swipwzoomorder = $_order->getSwipezoomOrderNumberTemp()){ }else{ ?> <strong>(<?php echo $_email ?>)</strong><?php } ?>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                    <td class="value"><strong><?php echo $orderAdminDate ?></strong></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                        <td class="value"><strong><?php echo $orderStoreDate ?></strong></td>
                    </tr>
                    <?php endif;?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                    <td class="value"><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                    <td class="value"><strong><?php echo $this->getOrderStoreName() ?></strong></td>
                </tr>
                <?php if($_order->getRelationChildId()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the New Order') ?></label></td>
                        <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                                <?php echo $_order->getRelationChildRealId() ?>
                            </a></td>
                    </tr>
                    <?php endif; ?>
                <?php if($_order->getRelationParentId()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the Previous Order') ?></label></td>
                        <td class="value"><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                                <?php echo $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                    <?php endif; ?>
                <?php if($_order->getRemoteIp() && $this->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                        <td class="value"><strong><?php echo $_order->getRemoteIp(); echo ($_order->getXForwardedFor())?' (' . $this->escapeHtml($_order->getXForwardedFor()) . ')':''; ?></strong></td>
                    </tr>
                    <?php endif; ?>
                <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                        <td class="value"><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
                    </tr>
                    <?php endif; ?>
                <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                        <td class="value"><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
                    </tr>
                    <?php endif; ?>
                      <?php
					   $newszorderid = $_order->getSwipezoomOrderNumberTemp();
					  $partshipreqcolleciotn1 = Mage::getModel('internationalshipping/partshipreq')->getCollection()->addFieldToFilter('newszorderid',$newszorderid);
					 if(count($partshipreqcolleciotn1)){
						 foreach($partshipreqcolleciotn1 as $part){ 
							$neworder = Mage::getModel('sales/order')->load($part->getRealorderid());
							$incrementid =  $neworder->getIncrementId();
							$parentorderid = $neworder->getId();
						
						 ?>
                         <tr> <td class="label"><label><?php echo Mage::helper('sales')->__('Original Order: ') ?></label></td>
						 <td class="value"><a href="<?php echo $this->getUrl('adminhtml/sales_order/view',array('order_id'=>$parentorderid))?>"><strong># <?php echo $incrementid; ?></strong></a></td>   </tr>
						 <?php }
				     }
					 
					 
					  
					  
					  
					 if($_order->getSwipezoomOrderNumberTemp()){
						 		$swipezoomparentorder =  Mage::getModel('internationalshipping/swipezoomcreditmemo')->getCollection()->addFieldToFilter('swipezoomorderid',$_order->getSwipezoomOrderNumberTemp()); 
								$swipezoomparentorder1=  Mage::getModel('internationalshipping/swipezoomcreditmemo')->getCollection()->addFieldToFilter('refswipezoomorderid',$_order->getSwipezoomOrderNumberTemp()); 
								if(count($swipezoomparentorder)){
										 foreach($swipezoomparentorder as $parentorder){
											$paretorderid = $parentorder->getReforderno();
											break;
										 }
										  $incrementid =  Mage::getModel('sales/order')->load($paretorderid)->getIncrementId(); ?>
						<tr> <td class="label"><label><?php echo Mage::helper('sales')->__('Refund Order: ') ?></label></td>
						 <td class="value"><a href="<?php echo $this->getUrl('adminhtml/sales_order/view',array('order_id'=>$paretorderid))?>"><strong># <?php echo $incrementid; ?></strong></a></td>   </tr>
										  
										 <?php
								}elseif(count($swipezoomparentorder1)){
									
										 foreach($swipezoomparentorder1 as $parentorder){
											$childorderid = $parentorder->getRealorderno();
											break;
										 }
										  $incrementid =  Mage::getModel('sales/order')->load($childorderid)->getIncrementId();  ?>
					<tr>	 <td class="label"><label><?php echo Mage::helper('sales')->__('Parent Order: ') ?></label></td>
						 <td class="value"><a href="<?php echo $this->getUrl('adminhtml/sales_order/view',array('order_id'=>$childorderid))?>"><strong># <?php echo $incrementid; ?></strong></a></td> 	    </tr>
                         <tr>
                         <td class="label"><label><?php echo Mage::helper('sales')->__('Swipezoom Rog Order No: ') ?></label></td>
                         <td class="value"><strong><?php echo $_order->getSwipezoomOrderNumberTemp(); ?></strong></td>
                         </tr>
										  
										<?php
								}
					 } 
					 
					
					 
					 
					 $partshipreqcolleciotn = Mage::getModel('internationalshipping/partshipreq')->getCollection()->addFieldToFilter('realorderid',$_order->getId());
					 if(count($partshipreqcolleciotn)){
						 foreach($partshipreqcolleciotn as $part){ 
						$neworder = Mage::getModel('sales/order')->getCollection()->addFieldToFilter('swipezoom_order_number_temp',$part->getNewszorderid());
						foreach($neworder as $neworderincrementid){ 
							$incrementid =  $neworderincrementid->getIncrementId();
							$childorderid = $neworderincrementid->getId();
						}
						if($incrementid){
						 ?>
                         <tr> <td class="label"><label><?php echo Mage::helper('sales')->__('Updated Order: ') ?></label></td>
						 <td class="value"><a href="<?php echo $this->getUrl('adminhtml/sales_order/view',array('order_id'=>$childorderid))?>"><strong># <?php echo $incrementid; ?></strong></a></td>   </tr>
						 <?php }}
				     }
					 
					 
				?>
					<?php if($_order->getSwipezoomOrderCreditmemo()>3){?>                    
                    	<script type="text/javascript"> 
							Event.observe(document,"dom:loaded",function(){
								 $$('[title="Credit Memo"]').each(function(el){
									el.update('<span><span><span></span>Credit Memo Confirm</span></span>') 
								 });
							});
						</script>
                    <?php } ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
            <div class="tools"><?php echo $this->getAccountEditLink()?></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                        <td class="value">
                            <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                                <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                                <?php else: ?>
                                <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                                <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                        <td class="value"><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
                    </tr>
                    <?php if ($_groupName = $this->getCustomerGroupName()) : ?>
                        <tr>
                            <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                            <td class="value"><strong><?php echo $_groupName ?></strong></td>
                        </tr>
                        <?php endif; ?>
                    <?php foreach ($this->getCustomerAccountData() as $data):?>
                        <tr>
                            <td class="label"><label><?php echo $data['label'] ?></label></td>
                            <td class="value"><strong><?php echo $data['value'] ?></strong></td>
                        </tr>
                        <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
            <div class="tools"><?php echo $this->getAddressEditLink($_order->getBillingAddress())?></div>
        </div>
        <fieldset>
            <address>
                <?php 

                    $shippingMethod = $_order->getData("shipping_method") ;
                    if(strpos($shippingMethod,"swipezoom") !== FALSE):
                        $formater   = new Varien_Filter_Template();
                        $attributes = Mage::helper('customer/address')->getAttributes();
                        $address = $_order->getBillingAddress();
                        $data = array();
                        foreach ($attributes as $attribute) {
                            /* @var $attribute Mage_Customer_Model_Attribute */
                            if (!$attribute->getIsVisible()) {
                                continue;
                            }
                            if ($attribute->getAttributeCode() == 'country_id') {
                                $data['country'] = $address->getCountryModel()->getName();
                            } else if ($attribute->getAttributeCode() == 'region') {
                                    $data['region'] = $address->getRegion();
                                } else {
                                    $dataModel = Mage_Customer_Model_Attribute_Data::factory($attribute,$address);
                                    $value     = $dataModel->outputValue($dataFormat);
                                    if ($attribute->getFrontendInput() == 'multiline') {
                                        $values    = $dataModel->outputValue(Mage_Customer_Model_Attribute_Data::OUTPUT_FORMAT_ARRAY);
                                        // explode lines
                                        foreach ($values as $k => $v) {
                                            $key = sprintf('%s%d', $attribute->getAttributeCode(), $k + 1);
                                            $data[$key] = $v;
                                        }
                                    }
                                    $data[$attribute->getAttributeCode()] = $value;
                            }
                        }
                        $formater->setVariables($data);
                        $swipezoomString =  Mage::getModel('sales/quote')->getCollection()->addFieldToFilter("entity_id", $_order->getQuoteId())->getData() ;
                        $swipezoomString  = $swipezoomString[0]["swipezoom_address_billing_string"];

                        $format = "{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}<br/>\n{{depend company}}{{var company}}<br />{{/depend}}\n".$swipezoomString."\n<br/>{{depend telephone}}T: {{var telephone}}{{/depend}}\n{{depend fax}}<br/>F: {{var fax}}{{/depend}}\n{{depend vat_id}}<br/>VAT: {{var vat_id}}{{/depend}}";

                        echo $formater->filter($format);
                        else:
                        echo $_order->getBillingAddress()->getFormated(true);
                        endif;
            ?></address>
        </fieldset>
    </div>
</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
                <div class="tools"><?php echo $this->getAddressEditLink($_order->getShippingAddress())?></div>
            </div>
            <fieldset>
                <address>
                    <?php 
                        $shippingMethod = $_order->getData("shipping_method") ;
                        if(strpos($shippingMethod,"swipezoom") !== FALSE):

                            $formater   = new Varien_Filter_Template();
                            $attributes = Mage::helper('customer/address')->getAttributes();
                            $address = $_order->getShippingAddress();
                            $data = array();
                            foreach ($attributes as $attribute) {
                                /* @var $attribute Mage_Customer_Model_Attribute */
                                if (!$attribute->getIsVisible()) {
                                    continue;
                                }
                                if ($attribute->getAttributeCode() == 'country_id') {
                                    $data['country'] = $address->getCountryModel()->getName();
                                } else if ($attribute->getAttributeCode() == 'region') {
                                        $data['region'] = $address->getRegion();
                                    } else {
                                        $dataModel = Mage_Customer_Model_Attribute_Data::factory($attribute,$address);
                                        $value     = $dataModel->outputValue($dataFormat);
                                        if ($attribute->getFrontendInput() == 'multiline') {
                                            $values    = $dataModel->outputValue(Mage_Customer_Model_Attribute_Data::OUTPUT_FORMAT_ARRAY);
                                            // explode lines
                                            foreach ($values as $k => $v) {
                                                $key = sprintf('%s%d', $attribute->getAttributeCode(), $k + 1);
                                                $data[$key] = $v;
                                            }
                                        }
                                        $data[$attribute->getAttributeCode()] = $value;
                                }
                            }
                            $formater->setVariables($data);
                            $swipezoomString =  Mage::getModel('sales/quote')->getCollection()->addFieldToFilter("entity_id", $_order->getQuoteId())->getData() ;
                            $swipezoomString  = $swipezoomString[0]["swipezoom_address_shipping_string"];

                            $format = "{{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}<br/>\n{{depend company}}{{var company}}<br />{{/depend}}\n".$swipezoomString."\n<br/>{{depend telephone}}T: {{var telephone}}{{/depend}}\n{{depend fax}}<br/>F: {{var fax}}{{/depend}}\n{{depend vat_id}}<br/>VAT: {{var vat_id}}{{/depend}}";

                            echo $formater->filter($format);

                            else:
                            echo $_order->getShippingAddress()->getFormated(true);
                            endif;
                    ?>
                </address>
            </fieldset>
        </div>
    </div>
    <div class="clear"></div>
    <?php endif; ?>
