
<?php $_order = $this->getOrder()

 ?>
<?php $swipwzoomorder = $_order->getSwipezoomOrderNumberTemp();
	$count = Mage::getModel('internationalshipping/packingdetail')->getCollection()->addFieldToFilter('swipezoomorderid',$swipwzoomorder);
	if(count($count)){ ?>
          <div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th width="70"><?php echo Mage::helper('sales')->__('Item') ?></th>
                <th width="120"><?php echo Mage::helper('sales')->__('Box Code') ?></th>
                <th width="70"><?php echo Mage::helper('sales')->__('Box No.') ?></th>
                <th width="500"><?php echo Mage::helper('sales')->__('Product Description') ?></th>
                <th width="150"><?php echo Mage::helper('sales')->__('Product Code') ?></th>
                <th width="70"><?php echo Mage::helper('sales')->__('Quantity') ?></th>
            </tr>
        </thead>
        <?php 
		$orderid = Mage::app()->getRequest()->getParam('order_id');
		$order= Mage::getModel('sales/order')->load($orderid);
		$swipwzoomorder = $order->getSwipezoomOrderNumberTemp();
		
		
		$_items = Mage::getModel('internationalshipping/packingdetail')->getCollection()->addFieldToFilter('swipezoomorderid',$swipwzoomorder); 
		//print_r($_items->getData());
		if(count($_items)){
		?>
        
        <tbody class="<?php echo $_i%2?'even':'odd' ?>">
		<?php $_i=0;foreach ($_items as $_item): ?>
        <?php if(!$_item->getProductcode()){break;}
		$products = Mage::getModel('catalog/product')->loadByAttribute('sku', $_item->getProductcode());
		if(!$products){ echo "<tr ><td colspan='6'>Somthing wrong Happen - Product not found.</td></tr>"; break;}
		?>
        <?php $_i++; ?>
        	<tr class="border">
            <td ><?php echo $_i ?></td>
		    <td><?php echo $_item->getBoxcode() ?></td>
            <td><?php echo $_item->getBoxno() ?></td>
            <td><?php 	echo $products = Mage::getModel('catalog/product')->loadByAttribute('sku', $_item->getProductcode())->getName(); 											//$productname = $_Pdetails->getName();
//			 $_item->getProductname() ?></td>
            <td><?php echo $_item->getProductcode() ?></td>
            <td><?php echo $_item->getProductqty() ?></td>
			</tr>
       <?php endforeach; ?>
        </tbody>
    </table>
    <?php }?>
  </div>
</div>  
<br />
<style>
.entry-edit-head .tools a{display:none;}
</style>
 <?php  }else{  ?> 

<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Item Status') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
                <th><?php echo $this->helper('sales')->__('Price') ?></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Percent') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
                <th class="last"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php  echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<br />
<?php } ?>
