<div class="page-title title-buttons">
  <h1>Print Packing Instruction</h1>
  <button onclick="window.parent.closePopup();" class="button"><span><span>Close Window</span></span></button>
</div>
<div class="content">

</div>
<div class="buttons-set">
  
  <button onclick="window.parent.closePopup();" class="button" title="Close Window" type="button"><span><span>Close Window</span></span></button>
</div>
