
<?php  $_order = $this->getCreditmemo()->getOrder() ?>
<?php echo $this->getChildHtml('order_info') ?>
<?php if (!$_order->getIsVirtual()): ?>
<div class="box-left">
<?php else: ?>
<div class="box-right">
<?php endif; ?>
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo $this->helper('sales')->__('Payment Information') ?></h4>
        </div>
        <fieldset>
            <div><?php echo $this->getChildHtml('order_payment') ?></div>
            <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
        </fieldset>
    </div>
</div>
<?php if (!$_order->getIsVirtual()): ?>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-method"><?php echo $this->helper('sales')->__('Shipping Information') ?></h4>
        </div>
        <fieldset>
            <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>
            <?php //echo $this->helper('sales')->__('Total Shipping Charges'); ?>

            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
            <?php else: ?>
                <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>
   <br />
             <?php echo $this->helper('sales')->__('Total Shipping Charges'); ?>:
                    <?php echo $_excl; ?>
            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
            <?php endif; ?>
             <br />
                    <?php 
					 $szOrderId = $_order->getSwipezoomOrderNumberTemp();
					 if($szOrderId){
						 $counts = Mage::getModel('internationalshipping/shipmentdetail')->getCollection()->addFieldToFilter('swipezoomorderid',$szOrderId);
						 if(count($counts)){
							foreach($counts as $sh)	{
								echo "Pickup Due : ".$sh->getPickupdue()."</br>";
								echo "Airway Bill # : ".$sh->getCourierwaybillno()."</br>";
							}
						}
					 }
					
					?>
        </fieldset>
    </div>
</div>
<?php endif; ?>
  <div class="clear"></div>
    <?php 
	 			 $shippingMethod = $_order->getData("shipping_method") ;
                if(strpos($shippingMethod,"swipezoom") !== FALSE){ ?>
					<div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Swipezoom Order Information') ?></h4>
            </div><fieldset>

                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Swipezoom Order #') ?><span class="price-notice"><span class="price">
                            <?php echo $_order->getSwipezoomOrderNumberTemp();  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Shipping Charges : ') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderShippingCharges(),true,false);  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Prepaid duties &amp; taxes : ') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderDutiesTaxes(),true,false);  ?></span></span></label>
                </div>

                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Insurance :') ?><span class="price-notice"><span class="price">
                            <?php echo Mage::helper('core')->currency($_order->getSwipezoomOrderInsuranceCharges(),true,false);  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Duties Taxes Prepaid :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderDutiesTaxPrepaid() == "Y")?"Yes":"No";  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Insurance Paid :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderInsurancePaid() == "Y")?"Yes":"No";  ?></span></span></label>
                </div>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Confirmation Call :') ?><span class="price-notice"><span class="price">
                            <?php echo ($_order->getSwipezoomOrderConfirmed() == "1")?"Ok":"Error";  ?>
                            </span></span></label>
                </div>
                
                <?php if($_order->getSwipezoomOrderConfirmed() == 0): ?>
                <div class="swipezoom-container">
                    <label for="swipezoom_insurance_taxes" class="progress-rate-label"><?php echo $this->__('Error Message :') ?><span class="price-notice"><span class="price"><?php echo $_order->getSwipezoomOrderConfirmedErrormessage();; ?>
                            </span></span></label>
                </div>
                <?php endif; ?>
               </fieldset>
              
    					  <style>
                         .entry-edit-head .tools a{display:none;}
						.swipezoom-container .price-notice {    float: right;}
						.swipezoom-container {    width: 50%;}						 
                         </style>
            </div>
					
				<?php } ?>
<div class="clear"></div>
<?php $_items = $this->getCreditmemo()->getAllItems() ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-products"><?php echo $this->helper('sales')->__('Items Refunded') ?></h4>
    </div>
</div>
<?php if (count($_items)): ?>
<div id="creditmemo_items_container">
    <?php echo $this->getChildHtml('creditmemo_items') ?>
</div>
<?php else: ?>
<div class="entry-edit">
    <fieldset><center><?php echo $this->helper('sales')->__('No Items') ?></center></fieldset>
</div>
<?php endif; ?>
<br />
<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Credit Memo History') ?></h4></div>
    <fieldset><?php echo $this->getChildHtml('order_comments') ?></fieldset>
</div>

<div class="box-right entry-edit" id="history_form">
    <div class="entry-edit-head"><h4><?php echo $this->__('Credit Memo Totals') ?></h4></div>
    <div class="order-totals"><?php echo $this->getChildHtml('creditmemo_totals') ?></div>
</div>
<div class="clear"></div>
<?php if($_order->getSwipezoomOrderNumberTemp()){ ?>
<script type="text/javascript">

                    Event.observe(document,"dom:loaded",function(){
						<?php if($_order->getSwipezoomOrderCreditmemo()<3 && $_order->getSwipezoomOrderNumberTemp()){ ?>
						
						 $$('[title="Print"]').each(function(el){
                         	el.update('<span><span><span></span>Print Packing Instruction</span></span>');
							<?php 		
									if ($_order->hasInvoices()) {
										foreach ($_order->getInvoiceCollection() as $inv) {
											$invIncrementIDs = $inv->getId();
										//other invoice details...
											break;
										} 
									}
						?>
							el.setAttribute("onclick", "setLocation('<?php echo $this->getUrl('adminhtml/sales_order_invoice/print',array('invoice_id'=> $invIncrementIDs)) ?>')");
							
						 });
						 <?php }else{  ?>

						 $$('[title="Print"]').each(function(el){
                         	el.remove(); 
						 });
						 <?php } ?>
						 
                    });

                </script>
                <?php } ?>